# Generated by Django 4.1.3 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(default='5306075800082', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='identification_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport Number'), ('ID', 'Identification Number')], default='ID', max_length=25),
            preserve_default=False,
        ),
    ]
