# Generated by Django 4.1.3 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
