# Generated by Django 4.1.3 on 2022-12-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_bankaccount_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='amount_currency',
        ),
    ]
