# Generated by Django 4.1.3 on 2022-12-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_bankaccount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccounttoken',
            old_name='account_id',
            new_name='account',
        ),
    ]
