# Generated by Django 4.1.3 on 2022-12-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_account_id_bankaccounttoken_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='beneficiary_account_number',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='beneficiary_bank_id',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='beneficiary_name',
        ),
    ]
