# Generated by Django 4.1.3 on 2022-12-25 10:38

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_bankaccounttoken_refresh_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=django_fsm.FSMField(default='NEW', max_length=50),
        ),
    ]
