# Generated by Django 4.1.3 on 2022-12-25 16:39

import api.apps.payments.models.bank_account
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='_account_id_data',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_account_id_data', hash_key=api.apps.payments.models.bank_account.get_hash_key, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccounttoken',
            name='refresh_token_expiry',
            field=models.DateTimeField(default=api.apps.payments.models.bank_account.default_token_expiry),
        ),
    ]
