# Generated by Django 4.1.3 on 2022-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_bankaccount__account_id_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='stitch_ref',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
