# Generated by Django 4.1.3 on 2023-01-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_transaction_running_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequestevent',
            options={'ordering': ['created']},
        ),
    ]
