# Generated by Django 4.1.3 on 2023-01-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_paymentrequestevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.bankaccount'),
        ),
    ]
